# Generated by Django 5.1.1 on 2025-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='win_count',
            field=models.BigIntegerField(default=113),
        ),
    ]
