# Generated by Django 5.1.1 on 2025-02-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(unique=True)),
                ('name2', models.CharField(unique=True)),
                ('name3', models.CharField(unique=True)),
                ('name4', models.CharField(unique=True)),
                ('name5', models.CharField(unique=True)),
                ('name6', models.CharField(unique=True)),
                ('name7', models.CharField(unique=True)),
                ('name8', models.CharField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
