# Generated by Django 5.1.1 on 2025-02-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_tourney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='name1',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name2',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name3',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name4',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name5',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name6',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name7',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='name8',
            field=models.CharField(),
        ),
    ]
