# Generated by Django 5.1.1 on 2025-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_tourney_name1_alter_tourney_name2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='tourney_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
