# Generated by Django 5.1.1 on 2025-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_tourney_tourney_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='winner_match1',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match2',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match3',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match4',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match5',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match6',
            field=models.CharField(),
        ),
        migrations.AddField(
            model_name='tourney',
            name='winner_match7',
            field=models.CharField(),
        ),
    ]
