# Generated by Django 5.1.1 on 2025-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_tourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_right',
            field=models.IntegerField(default=0),
        ),
    ]
