# Generated by Django 5.1.1 on 2025-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_match_score_left_match_score_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
    ]
