# Generated by Django 5.1.1 on 2025-02-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_match_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tourney_win_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
