# Generated by Django 5.1.1 on 2025-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_tourney_win_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(default='Undefined'),
        ),
    ]
