# Generated by Django 5.1.1 on 2025-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='longest_exchange',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='shortest_exchange',
            field=models.BigIntegerField(default=0),
        ),
    ]
