# Generated by Django 5.1.1 on 2025-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_match_longest_exchange_match_shortest_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hangman_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
